# 넘파이(Numpy)

파이썬에 기본 내장되어 있는 표준 데이터 구조는 매우 유연하고 좋으나, 수치적인 연산 과정에서는 느리다는 단점이 있습니다.

우리는 예를 들어 리스트에 서로 다른 여러 타입의 객체들을 넣을 수 있습니다. 이게 별거 아닌거 같아 보이지만, 서로 다른 객체들은

당연히 서로 다른 형태로 임의의 저장 공간에 저장되어있으므로, 같은 리스트의 성분들이라도 객체가 다르다면 그들에 접근하는대에 걸리는 시간은 꽤 깁니다.

세상에 공짜 점심은 없다고, 편리하고 유연한 대신에, 성능을 가격으로 내야하는거죠.

그 떄문에 파이썬의 데이터 구조들은 수치적 계산을 위해 쓸만은하지만, 그렇게 강력하지는 않습니다.

이번에 다룰 **넘파이**(Numpy)는 이러한 단점을 극복하기 위해 좀 더 효율적인 배열 타입으로 파이썬의 수치적 프로그래밍을 매우 이상적으로 만들어주며,

동시에 수치 계산을 위한 수많은 사랑스러운 기능들을 모두 포함하고 있는 모둘입니다.

넘파이는 보통 다음의 형태로 임포트됩니다.

In [1]:
import numpy as np

## 배열(Array)

넘파이가 가지고 있는 데이터 구조를 막 엄청 거창하게 말했으나, 사실 별거 아닙니다. 그냥 여러분이 알고 계시는 C/자바의 그 배열이에요.

C와 자바에서 배열은 파이썬의 리스트와 같이 복수의 객체를 저장하기 위한 데이터 타입이지만,

파이썬의 리스트와 달리 크기가 고정되어 있고, 단일 타입만을 저장할 수 있다는 특징이 있습니다.

넘파이의 배열은 이 배열을 그대로 파이썬 버젼으로 옮긴 친구에요.

좀 이상할 수 있습니다. 크기가 고정되어있고, 단일 타입(대부분 수치형)만을 저장한다는 점은 얼핏보면 단점처럼만 보여져서, 

파이썬에는 리스트가 있는데 굳이 그 단점을 가진 데이터 타입을 왜 쓰는지 의문이 드실텐데요, 

애초에 이러한 성질들은 맥락에 따라서 단점이 될 수도, 장점이 될 수도 있습니다. 우리의 수치적 프로그래밍의 맥락에서 방금 말한 단점은 오히려 장점이에요.

수치적 프로그래밍은 결국 계산의 이야기인데요, 파이썬의 리스트는 계산 시 안에 들어있는 놈들이 뭔지 하나씩 확인해야합니다.

경우에 따라 서로 다른 데이터 타입의 객체가 리스트에 들어있다면, 계산할 떄마다 객체의 종류에 따라서 저장 공간을 이리 저리 옮겨다녀야하기도하구요.

반면 배열은 그냥 데이터 타입을 하나 고정하기 떄문에, 확인? 그딴거 필요없이 화끈하게 그 데이터 타입에 맞는 연산이 가능하여 훨씬 빠릅니다.


#### 리스트를 통해 어레이를 생성하기

만약 `lst`라는 리스트가 주어진다면, 우리는 다음 명령어로 `lst`의 원소들을 포함하고 있는 배열을 생성할 수 있습니다.

~~~python
np.array(lst)
~~~


In [2]:
np.array([0,1,2])

array([0, 1, 2])

간단합니다. 그냥 리스트를 저기 넣으면 그 리스트의 성분으로 구성된 배열로 만들어버리는거에요.

근데 설명한대로, 넘파이의 배열은 모두 단일 타입의 객체로 구성되므로, 예를 들어 다음과 같은 배열을 정의한다면,

In [3]:
b = np.array([0, 1.01, 2, 3])
b

array([0.  , 1.01, 2.  , 3.  ])

그 결과물은 저기 있는 `0`, `1.01`, `2`, `3` 중 더 일반적이라고 할 수 있는 `1.01`의 `float`의 형태를 기본으로 한 배열이 생성됩니다.

하나라도 `float`가 섞여있으면 모든 놈들이 `float`가 되어버리는거죠.

만약 저기서 데이터 타입을 `float`이 아닌 `int`로 지정해주고싶다면, 다음과 같이 파라미터를 넣어서 해주시면 됩니다.

In [4]:
b = np.array([0, 1.01, 2, 3], dtype = int)
b

array([0, 1, 2, 3])

그러면 보시다시피 `1.01`을 명시적으로 정수화하여 `1`로 바꿔, 모두 정수형으로 구성된 배열이 생성됩니다.

요약하면 서로 다른 타입이 들어있을 경우, `np.array()`는 기본적으로 들어있는 모든 성분들을 다 고려하여 통일된 타입의 객체를 포함하기 위해서

가장 일반적인 타입을 골라서 자동으로 그 타입으로 구성된 배열을 생성합니다.

만약 위의 리스트 안에 스트링이 하나 들어있다면, 그 놈을 제외한 나머지는 모두 숫자이지만, 이들을 스트링화해도 되기 떄문에,

스트링 타입의 배열이 생성되게 됩니다.

물론 리스트, 사용자가 만든 커스텀 객체나 딕셔너리 등은 들어갈 수 없습니다. 애초에 수치적 프로그래밍을 위한 배열이라서 필요하지도 않구요.

근데 예외적으로, 리스트는 배열 안에 들어갈 수 있는 케이스가 있는데요, 하지만 그 순간 그 배열은 조금 의미가 달라집니다.

### 고차원 배열

고차원 배열은 C/자바에서 보시던 그 고차원 배열을 의미합니다. 위에서 말한 예외 상황이 바로 이 고차원 배열을 의미합니다.

일반적으로 리스트는 `np.array()`안에 넣을 수 없거든요? 고차원 배열은 그 일반적인 룰이 효력을 잃는 특수한 케이스입니다.

보통 1차원 배열을 하나의 벡터 등으로 생각할 수 있다면 고차원 배열은 행렬 등으로 이해하실 수 있죠.

우선 2차원 배열을 먼저 생각해볼게요.

만약 `np.array()` 안에 **길이가 같은** 리스트들을 넣는다면 2차원 배열을 생성됩니다.

In [5]:
np.array([[1,1,2],[1,3,4]])

array([[1, 1, 2],
       [1, 3, 4]])

우리는 길이가 3인 리스트를 두 개 넣었으므로, 순서대로 2행(리스트의 개수)에 3열(각 리스트의 성분 개수)짜리 행렬과 비슷한 배열이 생성됩니다.

이는 다음과 같은 표로 도식화할 수 있습니다.

| | 1열 | 2열 | 3열 | 
|:---: |:---: | :---: | :---: |
| 1행 | 1 | 1 | 2 |
| 2행 |1| 3| 4 |

따라서 만약 해당 배열의 2행 2열의 원소에 접근하려면, 우리는 `a[1,1]`이라는 호출 표현을 사용할 수 있습니다.

In [6]:
a = np.array([[1,1,2],[1,3,4]])
print(a[1,1])
a

3


array([[1, 1, 2],
       [1, 3, 4]])

`a[2,2]`가 아닌 `a[1,1]`인건 당연히 파이썬은 인덱스가 0부터 시작하기 떄문에 그렇습니다.

배열은 저장되어있는 값을 읽는 것 뿐아니라, 쓰는거도 가능하기 떄문에, 인덱싱으로 다음과 같이 값을 수정해줄 수도 있습니다.

In [7]:
a[1,1] = 13
a

array([[ 1,  1,  2],
       [ 1, 13,  4]])

2차원 배열은 결국 이렇게 `np.array()`안에 (길이가 같은) 리스트들의 리스트를 넣어서 생성이 가능했습니다.

3차원 배열은 이러한 2차원 배열로 이뤄진 배열입니다. 2차원 배열을 중첩시킨 놈이죠.

이렇게 계속해서 중첩하는 방법으로 우리는 2차원 이상의 고차원 배열을 정의할 수 있습니다.

#### 배열의 차원(Dimension)

결국 고차원 배열은 정사각(길이가 같은) 리스트들의 리스트가 여러 개로 중첩되어 생성되는 배열인데요, 이 구성 중첩의 개수를 차원이라고 합니다.

만약 우리가 `arr`라는 배열이 있다면, 이 배열의 차원은 다음의 키워드로 호출이 가능합니다.

~~~python
arr.ndim
~~~

위에서 정의한 배열 `a`는 리스트들의 리스트로 생성되므로(중첩이 2개죠), 차원은 2입니다 :

In [8]:
a.ndim

2

#### 모양(Shape)

2차원 배열은 결국 위에서 본대로 표 혹은 행렬로 이해할 수 있는데요, 이러한 표와 행렬 등은 그 모양이 행과 열의 개수로 결정됩니다.

이러한 모양은 다음과 같은 키워드로 확인이 가능합니다.

~~~python
arr.shape
~~~

이 키워드를 입력하시면 해당 배열 `arr`이 몇 행 몇 열인지의 정보가 투펠에 담겨서 나옵니다.

In [9]:
a.shape

(2, 3)

설명한대로 결국 2행 3열이니, `(2,3)`이 튀어나오는걸 확인할 수 있습니다.

n차원 이상의 경우, 우리는 축이 하나 더 생기는거니 성분이 n개인 투플이 튀어나옵니다.

$n = 3$인 경우엔 `(depth, row,column)`의 순서로 모양이 튀어나옵니다.

예를 들어 다음의 3차원 배열을 보시죠.

In [10]:
a = np.array([
                [[0, 1, 2, 3, 0], [4, 5, 6, 1,7], [1,2,3,4,5]], # 3행 5열의 2차원 배열을
                [[0, 1, 2, 3, 0], [4, 5, 6, 1,7], [1,2,3,4,5]]  # 똑같은 놈들 가져와서 중첩시킴
            ])
a.shape

(2, 3, 5)

저기서 우리는 3행 5열의 2차원 배열을 중첩시켜서 3차원 배열을 정의하는데요, 

중첩되는 2차원 배열은 2개이고, 각 배열은 3행 5열이고, 이걸 순서대로 `(2,3,5)`로 반환하는거죠.

`depth`는 이러한 중첩이 몇 개의 2차원 배열로 이뤄졌는지를 보여주는 숫자입니다.

참고로 이렇게 3차원 배열을 하면, 인덱싱의 순서도 마찬가지로 `[depth, row, column]`입니다 :

In [11]:
print(a[1]) # a의 2번째 층을 출력합니다. 2번째 층은 2번째로 중첩된 2차원 배열입니다.
a[1].shape

[[0 1 2 3 0]
 [4 5 6 1 7]
 [1 2 3 4 5]]


(3, 5)

**주의할 점**: 행벡터 및 열벡터는 `(1,n)` 및 `(n,1)`의 `shape`를 가지는 2차원 벡터로 구현되는 경우가 많습니다.

그냥 1차원 배열로 벡터를 정의하면 되는거 아닌가? 하실 수 있는데요, 행벡터와 열벡터를 구분하는 시점에서 우리는 행과 열의 방향을 고려해야합니다.

그런데 1차원 배열은 그런 방향을 전혀 고려하지 않아서, 행벡터인지 열벡터인지를 말할 수 없죠.

따라서 수학적 프로그래밍을 하는 경우에는 일부러 행벡터/열벡터를 1차원 배열이 아닌 2차원 배열로 정의하는 경우가 많습니다.

In [12]:
undirected_vector = np.array([1,2,3]) #얘는 방향 없이 성분 정보만 있는 데이터 덩어리일 뿐입니다.
print(undirected_vector,undirected_vector.shape)

row_vector = np.array([
                        [1, 2, 3]
                      ])  # 얘는 1행 3열짜리 벡터로만 이뤄진 2차원 배열(행렬), 즉 행벡터입니다.
print(row_vector,row_vector.shape)

[1 2 3] (3,)
[[1 2 3]] (1, 3)


## 자주 사용되는 배열들

배열을 위와 같이 수동으로 직접 값을 입력해서 정의하는 경우도 있으나, 수학적 프로그래밍을 하다보면 자주 사용되는 구조의 배열들이 있습니다.

이런 구조들을 손쉽게 구현하기 위해 `numpy`에는 이를 위한 함수들이 미리 내장되어 있는 경우가 많습니다.

이러한 함수들 중 자주 사용되는 친구들을 좀 보고 넘어가도록 하겠습니다.

#### arange()

array + range로 이름이 붙은 `arange`는 기존의 내장된 데이터 구조였던 `range`를 배열 형태로 생성한 놈입니다. 

~~~python
np.arange(start=0, stop, step=1)
~~~
문법도 똑같아요.

In [13]:
a = np.arange(4)
print(np.arange(4))
a

[0 1 2 3]


array([0, 1, 2, 3])

위와 같이 `np.arange(4)`를 선언하면, ` a`에는 0부터 4-1 = 3까지의 숫자를 담은 배열이 생성됩니다.

이렇게 생각하실수도 있어요. 

*`range`는 애초에 리스트랑 달리 엄청 빠른 형태의 데이터 구조 아니냐? 그냥 그대로 `range`를 쓰면 썼지, 왜 굳이 `np.arange`가 필요한가?*

맞는 말입니다. 배열이 필요했던게 수치적으로 파이썬의 데이터 구조들이 비효율적이고 느려서였던걸 생각하면, 그렇게 생각할만하죠.

하지만 우리는 왜 `range`가 빠른지를 생각해볼 필요가 있습니다.

`range`는 어떤 값을 항상 담고 있는 그런 구조가 아니라, 제너레이터의 구조입니다. 

시작값과 끝값, 그리고 보폭을 기억해서 순서대로 그 값들을 생성하는 그런 구조죠. 

리스트와 달리 숫자를 어디 저장할 필요도 없고, 우리가 지금 필요한 게 `range`의 몇번째 성분인지만 알고 있다면, 

시작값, 끝값, 보폭을 토대로 해당 값을 즉시 연산 후 반환하기 떄문에 리스트보다 훨씬 빠르고 효율적으로 값들을 사용 가능했던겁니다.

한 마디로, 값을 담고 있지 않기 떄문에 빨랐던거죠. 그런데 이건 수치적 계산을 할 때 좋지 않습니다.

수학에서 우리는 하나의 데이터 구조에다가 어떤 연산을 적용해야 할 경우가 있는데요, `range`는 구조적으로 값을 직접 담고있지는 않다보니,

거기다가 연산을 시킬 수 없습니다. 그래서 직접 값을 담을 수 있는 구조들 중에 리스트의 비효율적인 면을 개선한 `np.arange()`를 사용하는겁니다.

또한 `range`에서 지정할 수 있는 시작값, 끝값, 보폭이 모두 정수형이라는 단점이 있는데요, `np.arange()`는 부동소수형으로 사용할 수 있다는 장점도 있습니다.

**주의할 점** : `range(start,stop,step)`을 실행한다면, `start`부터 출발하여 `stop-1`까지의 숫자가 `step`의 보폭으로 생성됩니다.

`range`의 경우에는 이 시작값, 끝값, 보폭이 모두 정수형이므로, 크게 혼동될 일이 없는데요.

반면 `arange(start, stop, step)`에서는 시작값, 끝값, 보폭이 부동소수형인 경우도 허용되므로, 좀 주의하실 필요가 있습니다.

이 놈은 `start`부터 출발하여 `stop`보다 작은 모든 숫자들을 생성합니다.

예를 들어서 `range(1,3)`은 다음과 같이 1, 2 까지 생성하지만,

In [14]:
list(range(1,3))


[1, 2]

`np.arange(1,3.4)`는 다음과 같이 1, 2, 3이 들어있는 배열을 생성합니다.

In [15]:
np.arange(1,3.4)

array([1., 2., 3.])

1은 일단 3.4보다 작으니, 무조건 포함되고, 다음 1 + 1 = 2도 3.4보다 작으니 포함, 다음 2 + 1 = 3도 3.4보다 작으니 포함되는겁니다.

혹시나 `range`처럼 $3.4 - 1 = 2.4$이니, 1, 2까지만 생성하지 않을까 오해하실까봐 덧붙입니다.

또한 저렇게 인자로 부동소수가 넘어가는 경우, 결과물은 항상 부동소수들의 배열이 됩니다.

#### linspace()

`linspace`는 `arange`와 비슷하나, 조금 다른 방법으로 배열을 생성합니다. `linspace`는 linear + space(linearly spaced) 가 합쳐진 이름입니다. 

~~~python
np.linspace(start, stop, npoints)
~~~

`arange`와 같이 시작값과 끝값 사이의 숫자들을 생성하나, `arange()`는 시작값으로부터 어떤 보폭으로 숫자를 키워나갈지를 지정하는 `step`을 넣지만,

`linspace`는 그 사이의 숫자들을 몇 개나 생성할지를 정하는 `npoints`라는 파라미터를 넣습니다.

예를 들어 `np.linspace(-1,1,4)`라는 명령어는 -1부터 1까지 총 4개의 숫자를 생성하라는 의미입니다.

In [16]:
ls = np.linspace(-1, 1, 4)
ls

array([-1.        , -0.33333333,  0.33333333,  1.        ])

이 때, 시작값과 끝값은 항상 해당 배열에 포함되며, 각 점들은 모두 같은 거리(equidistant)로, 말 그대로 선형적인 형태로 생성됩니다.

#### 영배열(zeros)

영배열은 말 그대로 0으로만 이뤄진 배열을 의미합니다.

~~~python
np.zeros(shape)
~~~
위에서 다룬 배열의 `shape` 형태(투플)로, 배열의 형태만 지정해준다면 `np.zeros(shape)`는 그 `shape`에 맞는 배열에 모두 0을 넣은 놈을 생성합니다.

빈 그릇을 만드는거죠.

In [17]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

보시면 알겠으나 `zeros()`는 저렇게 모든 성분들을 `float`으로 간주한 배열을 생성합니다.

만약 이미 `a`라는 배열이 주어져있고, 이 배열과 똑같은 모양이지만 0으로만 구성된 친구를 만들고 싶다면

우리는 `np.zeros_like(a)`라는 명령어를 사용할 수 있습니다.

In [18]:
a = np.array([
    [1,2,3],
    [3,4,5]
])

np.zeros_like(a)

array([[0, 0, 0],
       [0, 0, 0]])

말 그대로 `zeros like a`(마치 a와 같은 영 배열)을 생성하는겁니다.

#### 일배열(ones)

위의 영배열은 0.0으로만 이뤄진 배열을 생성하는거였다고 하면, 일배열은 1.0로만 이뤄진 배열을 생성하는겁니다.

~~~python
np.ones(shape)
~~~
문법은 똑같습니다.

In [19]:
print(np.ones((2, 3)))

np.ones_like(a)

[[1. 1. 1.]
 [1. 1. 1.]]


array([[1, 1, 1],
       [1, 1, 1]])

마찬가지로 `np.ones_like()`도 가능합니다.

#### 항등 행렬(eye)

2차원 배열은 수학적인 입장에서 행렬로 생각할 수 있는데요, 우리는 항등 행렬을 생성하고 싶을 때가 있을텐데, 이는 다음의 키워드로 가능합니다.

~~~python
np.eye(dim)
~~~

저걸 입력하시면 `dim` $\times$ `dim` 형태의 항등 행렬을 생성합니다.(2차원 배열만 가능합니다.)

In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 대각 행렬(diag)

마찬가지로 대각 행렬도 자주 사용되는 친구인데요, 이 놈은 다음과 같이 생성 가능합니다.

~~~python
np.diag(vector, k=0)
~~~

간단합니다. `vector`는 대각 성분으로 올 친구들을 모은 리스트가 오구요, `k`는 대각선을 기준으로 얼마나 옆으로 갈지를 결정합니다.

일단 바로 사용해보시죠.

In [21]:
v = np.array([3, 1, 4, 1])
np.diag(v)

array([[3, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 1]])

바로 이해가 되실겁니다. k는 아직 뭐하는 놈인가 싶으실 수 있으나, 눈으로 보면 빠르게 이해가 될겁니다.

In [22]:
np.diag(v, k=1)

array([[0, 3, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0]])

행렬의 진짜 대각선을 우리는 주 대각선(Main diagonal)이라 하는데요, `k`는 주 대각선을 기준으로 어떤 방향으로 성분들을 넣을건지를 결정합니다.

주 대각선의 오른쪽 위의 대각선을 상대각선(Super diagonla)이라 하는데, `k=1`을 하면 `vector`의 성분이 상 대각선에 오는 배열이 생성됩니다.

마찬가지로 `k = -1`을 하면 다음과 같이, 주 대각선을 기준으로 왼쪽 아래 대각선(하대각선, subdiagonal)에 `vector`의 성분들이 들어옵니다.

참고로 크기가 `n`인 벡터 `v`라고 하더라도, 이 `v`의 성분이 주대각선에 온다면, 그 배열은 $n\times n$의 배열이 됩니다.

하지만 `v`의 성분들이 주 대각선이나 부 대각선으로 가는 경우, 크기가 달라집니다. 이걸 유의하셔야해요 :

In [23]:
np.diag(v, k =-1) + np.diag(v) # 전자는  5x5 행렬, 후자는 4x4 행렬이라 연산이 안됩니다.

<class 'ValueError'>: operands could not be broadcast together with shapes (5,5) (4,4) 

## 인덱싱과 슬라이싱

위에서도 조금 언급했었는데요, 배열도 리스트와 비슷한 형태로 인덱싱으로 쓰기/읽기가 가능합니다.

더 나아가 리스트처럼 슬라이싱도 가능합니다.

~~~python
array[start1:stop1:step1, start2:stop2:step2, ...]
~~~

슬라이싱의 아이디어는 똑같아요. 아래와 같은 `arange`가 주어진다면

In [24]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

우리는 이 놈의 첫번째, 5번째 성분을 다음과 같이 불러올 수 있습니다.

In [25]:
print(a[0])
print(a[4])

0
4


기존의 리스트와 마찬가지로 음수 인덱싱도 가능합니다 :

In [26]:
print(a[-1])

9


슬라이스도 똑같아요

In [27]:
a[:7]

array([0, 1, 2, 3, 4, 5, 6])

In [28]:
a[:-1:2]

array([0, 2, 4, 6, 8])

고차원 배열에서도 마찬가지입니다.

In [29]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a)
print(a[1, 0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
4


다만 주의할 점은, 저 인덱스의 순서에요. 2차원은 딱 보시다시피 `[row, column]`의 순서로 인덱싱되는데요,

3차원부터는 `[depth, row, column]`의 순서로 인덱싱됩니다.

슬라이싱도 똑같습니다 :

In [30]:
a[::2, :]

array([[1, 2, 3],
       [7, 8, 9]])

In [31]:
a[1, :]

array([4, 5, 6])

In [32]:
a[:, 1]

array([2, 5, 8])

In [33]:
a[:, 1:2]

array([[2],
       [5],
       [8]])

In [34]:
a[ 1:2, :].shape

(1, 3)

In [35]:
a[:,1].shape

(3,)

고차원 배열의 슬라이싱은 해당 배열의 부분 배열(행렬이라 치면 소행렬같은 친구들)을 가져오기 위해 사용할 수 있습니다.

더 나아가 배열은 인덱싱/슬라이싱을 통한 쓰기(값의 변경)도 지원하기 떄문에, 배열의 특정 부분의 값을 변경하기 위해서도 사용 가능합니다.

In [36]:
a = np.arange(1, 10)
print(a)
a[:3] = np.array([-1, -2, -3])
print(a)

[1 2 3 4 5 6 7 8 9]
[-1 -2 -3  4  5  6  7  8  9]


## 스태킹과 스플리팅

배열은 모두 `shape`를 가지고 있는데요, `arr.shape`로 반환되는 투펠들의 각 성분들을 축(Axis)이라고 합니다.

예를 들어
```python
a = np.array([1, 2, 3])
b = np.array([[1, 3],[3, 4]])
```

이런 두 배열이 있다면, `a.shape`는 `(1,)`이므로, 축이 하나이고, `b.shape`는 `(2,2)`이므로 축이 두 개입니다.

우리는 주어진 이런 배열의 모양, 배열의 축에 따라서 서로 다른 복수의 배열들을 합칠 수 있습니다.

### 스택(Stack)

먼저 완전 `shape`가 동일한 배열들은 새로운 축을 만들어서, 그 축의 위에다가 쌓아올리는 식으로 합치기가 가능합니다. 이를 위한 명령어는 다음과 같습니다.

```python
    np.stack(arrays, axis=0)
```

`arrays`에는 배열들이 여러 개 들어있는 리스트나 투플이 들어옵니다. 스택은 말 그대로 이 `arrays`에 들어있는 여러 배열들을 쌓는다는 의미입니다.

예를 들어 2차원 배열들은 평면적인 종이로 생각할 수 있는데요, 얘네들을 스택한다는건 얘네들을 쌓아올려서 3차원인 책을 만들겠다는거에요.

결국 스택을 하면 새로운 차원이 하나 생겨서, 그 차원을 기준으로 배열들을 합치게 되는데요, 이는 배열의 생성 방식을 생각한다면

배열들에다가 대괄호 `[]`를 하나 더 치는걸로 이해할 수 있습니다. 이 때, `axis`는 이 대괄호를 어디에 칠지 결정합니다.

예를 들어서

```python
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arrays = [arr1, arr2]
```
이런 1차원 배열들의 리스트를 가지고, 다음과 같이 스택한다면

```python
np.stack(arrays, axis = 0)
```
이는 결국 `[[1,2,3], [4,5,6]]`의 형태로, 가장 바깥쪽에 대괄호를 쳐서 스택을 하라는 의미가 됩니다.

근데 만약

```python
np.stack(arrays, axis = 1)
```
을 하게 된다면, 더 안 쪽으로 들어가서, 안에 있는 원소들끼리 대괄호를 친 `[[1,4], [2,5], [3,6]]`의 형태가 됩니다


In [37]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arrays = [arr1, arr2]

In [38]:
np.stack(arrays, axis = 0)

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
np.stack(arrays, axis = 1)

array([[1, 4],
       [2, 5],
       [3, 6]])

이 `axis`가 좀 어려울 수 있는데요, 간단히 생각하면 됩니다.

`axis = 0`인 경우에는 별로 생각할 필요 없이, 어떤 창고에다가 `arrays`에 배열 상자를 그대로 넣는다는 의미입나다.

그렇게 상자들을 창고에 넣은 다음 창고 자체를 반환하는거죠.

`axis = 1`인 경우에는 더 들어가서, 각 상자의 내용물끼리 짝을 지어서 상자를 만들어서 창고에 넣는거에요.

위 예시에서는 첫번쨰 상자인 `[1,2,3]`에서의 `1`과 `[4,5,6]`의 `4`를 짝짓고, 다음은 `2`와 `5`, 그 다음은 `3`과 `6` 이런식으로요.

만약 `axis = 2`라면, 이 내용물의 내용물끼리 짝을 짓는겁니다. 하지만 위의 1차원 배열에서는 `axis = 2`가 불가능하죠. 내용물이 이미 가장 작은 단위이니까요.

### 순차(Concatenate)

위에서는 같은 `shape`인 배열들을 새로운 축 위에 쌓아올려서 합치는 방법을 다뤘는데요,

이번엔 같은 `shape`인 경우, 기존에 존재하던 축에 이어서 합치는 순차를 다뤄보려고 합니다.

뭐 말이 어렵지, 기존의 리스트를 이어붙이는거랑 같은 이야기에요. 이는 `np.concatenate()`함수를 이용하시면 됩니다.

```python
   np.concatenate(arrays, axis=0)
```

말 그대로 이어붙이는거에요. 만약 위에서의 예시와 같이

```python
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arrays = [arr1, arr2]
```
에다가 `np.concatenate(arrays, axis = 0)`을 한다면, 그 결과물은 `np.array([1,2,3,4,5,6])`이 됩니다.

이 순차의 맥락에서 `axis`는 이 이어붙이는걸 어느 방향으로 할지를 결정합니다. 지금 예시처럼 1차원 배열들을 이어 붙인다면,

따로 방향이 없으니 저렇게 순차적으로 뒤에 꼬리를 물도록 이어지는데요,

만약 2차원 배열들을 합치는 경우, 2차원 배열들을 행방향으로 이을 것인가, 열 방향으로 이을 것인가에서 차이가 있는데요,

`axis = 0`은 행방향, `axis = 1`은 열방향으로 생각하시면 됩니다. `axis = 0`인 경우는 다음과 같이 합쳐집니다.

$$
\begin{pmatrix} 1 & 2\\ 3 &4\end{pmatrix}\quad,\quad \begin{pmatrix} 5& 6\\ 7 & 8 \end{pmatrix}\qquad \overset{axis = 0}{\Rightarrow} \qquad\begin{pmatrix} 1 & 2\\ 3 &4\\5& 6\\ 7 & 8\end{pmatrix}
$$

눈치채셨겠지만, `axis`의 값은 배열의 `shape`의 순서와 동일합니다. 3차원 배열들을 순차하는 경우, 

`(depth, row, column)`의 `shape`에서 어떤 방향으로 이어 붙일건가를 `axis`로 지정하는거에요.

2차원의 경우엔 `(row, column)`이 `shape`니까, `axis = 0`이 행, `axis = 1`이 열이 되는거구요.

### 특수한 경우

위의 스택 혹은 순차 외에도 자주 사용되는 합치는 방식이 있습니다.

```python
np.hstack(arrays)
``` 
우선 위의 놈은 `arrays`들을 수평으로 이어 붙입니다. 이는 1차원의 배열들로 생각한다면 `concatenate(arrays, axis=0)`와 동일한 역할을 합니다.

그리고 2차원 이상의 경우, `concatenate(arrays, axis=1)`으로 배열을 이은 놈이 정의됩니다.

`arrays`에 2차원 배열들이 들어있는 경우에는 열방향으로 배열들이 이어지며, 3차원인 경우에는 행방향으로 배열들이 이어집니다.

horizontal이라면서 3차원에서 행방향으로 이어지는게 좀 헷갈리실 수도 있는데요, 그냥 `axis = 1`이 기준이다 정도로 생각하시면 됩니다.

반대로 행이 `axis = 0`을 기준으로 늘어나는 놈은 다음을 이용하시면 됩니다.

```python
np.vstack(arrays)
``` 
마찬가지로 이 친구는 1차원 배열들이 주어졌을 땐 `stack(arrays, axis=0)`, 2차원 이상일 경우에는 `concatenate(arrays, axis=0)`로 쌓아집니다.

### 스플리팅(Splitting)

합치는 것과 반대로 우리는 배열을 쪼갤 수도 있습니다. 이 때, 쪼개는 기준은 축이 됩니다.


```python
    np.split(array, nparts, axis=0)
    np.split(array, (idx1, idx2, ...), axis=0)
```
우선 위의 놈을 설명하자면, `array`라는 배열을 축 `axis = 0`을 기준으로, `nparts`개의 (같은 크기의) 배열로 쪼개라는 의미가 됩니다.

만약 `nparts`로 배열을 균등하게 쪼갤 수 없다면(즉 `axis` 방향의 길이가 `nparts`로 나누어떨어지지 않는다면), 에러가 발생합니다. 까다로운 친구죠.

그리고 아래의 놈은 반대로, 우리가 직접 배열의 `axis`의 몇 번째 몇 번째 지점에서 쪼갤지를 지정하기 떄문에, 그런 에러는 방생하지 않아요.

어쨌든 이 `split()`함수는 쪼개진 배열들을 담은 리스트를 반환합니다. 리스트도 다중 할당이 가능해서, 예를 들어 다음의 명령이 가능합니다.

```python
 first, second, third = np.split(array, (4, 6))
```
이렇게 한다면 각 `first`, `second`, `third`에는 다음과 같은 형태로 쪼개진 놈이 들어가게 됩니다.

```python
    first = array[:4] # 0부터 4-1 = 3까지의 원소(총 4개)
    second = array[4:6] # 4부터 6-1 = 5까지의 원소(총 2개)
    third = array[6:]  # 6부터 끝까지의 원소(나머지)
```

## 복사, 레퍼런스, 뷰

배열 객체는 기존의 다른 컨테이너 객체처럼 레퍼런스를 이용하므로, 값이 변경될 때 부작용(Side Effect)이 있을 수 있습니다.

In [40]:
import numpy as np

a = np.arange(5)   
b = a            # b는 결국 a가 가리키고 있는 것과 같은 배열 객체를 가리킴.
b[2] = -1        # 따라서 b[2] = -1로 b가 가리키고 있는 친구의 값을 변경하면
a                # a에서도 그 변경이 똑같이 적용됨. a와 b는 같은 대상을 가리키는거니까

array([ 0,  1, -1,  3,  4])

이건 이미 다른 프로그래밍 언어나 파이썬의 다른 컨테이너에서도 확인하셨을겁니다.

보통 단순한 객체들(`int`, `float`)는 객체의 값을 변경할 수 없으므로, 위와 같은 문제가 발생하지 않습니다.

만약 `a = 1`를 정의하고 `b = a`라 한다면, 이 시점에서 `b`는 `a`에 들어있는 `1`을 복사하여, `b`는 이 복사본을 가리키거든요.

In [41]:
a = 1
b = a

b = -1111
print(a,b)

1 -1111


한 마디로 단순한 데이터 타입들은 저렇게 값을 복사하지만, 배열(및 콘테이너)은 복사하지 않기 떄문에 부작용이 발생한다는 이야깁니다.

근데 가끔은 레퍼런스가 아니라, 진짜 말 그대로 같은 구조의 배열을 새로 만들어서 가리키는, 즉 배열을 복사하는 게 필요할 수 있는데요,

이는 `copy()`메소드를 이용하여 구현 가능합니다 :

In [42]:
a = np.arange(5)
b = a.copy() # 이번엔 a가 가리키는 친구를 직접 가리키는 게 아니라, a가 가리키는 놈의 복사본을 새로 생성해서 그걸 가리킴

b[2] = -1    # 따라서 이렇게 값을 변경하면 b는 a랑 관계없는, a가 가진 배열의 복사본의 값을 변경하는거므로, 부작용이 없음
print(a,b)   # a값은 변경되지 않고, 원하는대로 b 값만 변경되는걸 확인 가능

[0 1 2 3 4] [ 0  1 -1  3  4]


이 `copy()`메소드는 배열 뿐 아니라 파이썬에 내장된 많은 가변 객체들(리스트, 딕셔너리, 집합 등)도 가지고 있는 메소드입니다.

배열에 한해서는 슬라이스도 똑같은 부작용 문제가 있습니다.

In [43]:
a = np.arange(5)
b = a[::2]  # 배열을 슬라이스 하는건 a가 가리키는 놈의 일부를 가리키는거기 떄문에, 똑같이 부작용이 발생합니다.
print(a,b)
b[2] = -1   # b의 2 + 1 = 3번째 원소를 -1로 바꾸면, 이는 a의 4 +1 = 5번째 원소도 같이 바뀝니다.
print(a,b)

[0 1 2 3 4] [0 2 4]
[ 0  1  2  3 -1] [ 0  2 -1]


물론 리스트는 슬라이스할 때마다 그 슬라이스 성분들로 구성된 새로운 리스트를 정의하므로, 이런 문제가 발생하지 않지만, 배열은 그렇다는거에요.

그 이유는 이렇게 슬라이스를 할 때, `b`는 정확히 말하자면 `View`라는 객체를 생성하기 떄문입니다.

`View`가 된다는건 다시 말해서, 원하는대로 슬라이싱 된 형태를 말 그대로 보여주는 View의 역할을 한다는거에요.

근데 보여준다는건, 새로운 복사본을 만든다는 게 아니라, 말 그대로 그 원본의 일부 부분을 보여준다는 의미이기 떄문에 저렇게 부작용이 발생하는겁니다.

만약 필요한 경우 우리는 저렇게 슬라이스를 하지 않더라도 명시적으로 `view()`메소드로 명시적으로 뮤 객체를 생성할 수 있습니다.

In [44]:
a = np.arange(6)
print(a)
b = a.view()

[0 1 2 3 4 5]


이 경우, `b`는 마찬가지로 원본인 `a`와 동일한 데이터를 가지고 있는 배열을 가리키나, `shape` 등의 메타 데이터를 공유하지는 않습니다.

따라서 `b`의 `shape`를 바꾸더라도 `a`에는 영향이 없으나, `b`의 값을 바꾸면 `a`에서도 그 변화가 업데이트됩니다.

In [45]:
# b의 모양을 바꾸면 그건 b에 반영됨
b.shape = (2,3)
print(b)

print(a) # 하지만 a는 안 바뀜

[[0 1 2]
 [3 4 5]]
[0 1 2 3 4 5]


In [46]:
# shape와 달리, 값을 직접 변경하는건 a에도 반영됩니다.
b[0][0] = 10

print(a)
print(b)

[10  1  2  3  4  5]
[[10  1  2]
 [ 3  4  5]]


이러한 부작용은 특히나 함수에 배열을 넘겨줄 떄 조심해야합니다.

아시다시피 리스트 등과 마찬가지로 배열도 `call by reference`라는 방식으로 작동하므로, 함수에 전달된 후, 함수 내부에서 값이 변경된다면

그게 함수를 떠난 후에도 계속 유지됩니다.

#### 복사와 삭제

수치 프로그래밍에서는 이러한 부작용을 꽤 많이 의식해야합니다. 데이터를 아끼기 위해서 수치적 알고리즘은 보통 인플레이스로 동작하는데요,

이런 배열과 `View`의 관계를 의식하지 않으면 원본 데이터가 오염되는 문제가 발생할 수도 있어서 주의하셔야해요.

만약 이걸 원천 차단하고자한다면, 특정 배열의 부분을 복사할 수도 있습니다.

뷰 대신에 실제 슬라이스된 복사본을 얻으려면 `copy()`메소드를 활용할 수 있습니다.

~~~python
np.copy(arr)
arr.copy()
~~~

In [47]:
a = np.arange(5)
b = a[::2].copy()

print(a,b)

b[2] = -1
print(a,b) # 이번엔 a는 안바뀝니다. b는 copy()로 생성된 새로운 슬라이스 복사본을 가리키니까요.

[0 1 2 3 4] [0 2 4]
[0 1 2 3 4] [ 0  2 -1]


복사본이 만들어진 이후에 원본이 필요하지 않은 경우 등에는 레퍼런스 객체는 삭제하는 게 좋습니다.

여러 이름표를 달고 있으면 오류가 생길 가능성이 높아지니까요. 이를 위해서는 명령어 `del`을 사용하시면 됩니다.

In [48]:
a = np.arange(5)
del a
a # a가 삭제되었으므로, 파이썬이 a가 뭔지 모름

<class 'NameError'>: name 'a' is not defined

## `reshape`와 `transpose`

#### `reshape`

`reshape`는 기존에 주어진 배열의 모양을 바꾸는 메소드입니다.

~~~python
arr.reshape(newshape)
~~~

`reshape`는 말 그대로 지정된 `newshape`에 따라서 배열의 모양만을 변경하며, 배열의 값은 변경하지 않습니다.

하지만 정확하게 말하면, 진짜 `arr.shape`를 바꾸는 게 아니라, `arr`을 `newshape` 모양으로 보여주는 View 객체를 생성하여 반환합니다.

따라서 `reshape()`를 사용하더라도 원본 `arr`의 `shape`는 전혀 변하지 않습니다.

물론 모양은 항상 우리가 가진 `arr` 배열의 데이터들이 정확히 들어설 수 있는 형태가 되어야 합니다. 조금이라도 어긋나면 에러가 뜹니다.

In [49]:
a= np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [50]:
a.reshape((3, 8))

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

설명한대로 저렇게 `reshape`를 하더라도, `a`의 `shape`는 그대롭니다 :

In [51]:
a.shape

(24,)

위에서처럼 `(3,8)`로 3행 8열을 직접 지정할 수도 있는데요, 우리는 예를 들어 행만을 지정하고, 나머지는 니 알아서 하라고 할 수도 있어요 :

In [52]:
a.reshape((4, -1)) # (4,-1)은 행은 4개로 하는데, 열은 그거에 맞춰라는 의미가 됩니다.

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

실제로 `shape`를 바꾸려면 `a.shape = (3,-1)`과 같이 모양을 지정해야합니다. 이 때도 칸이 딱 맞게 사용하셔야합니다.

#### 배열을 1차원으로 변환하기

`reshape()`는 이렇게 특정 모양으로 만들어버리는 메소드였는데요,

반대로 어떤 특정 모양의 배열을 `ravel()`이라는 메소드로 배열을 1차원으로 만들 수도 있습니다. 물론 이 경우에도 View가 생성되는겁니다.

~~~python
arr.ravel()
~~~

In [53]:
np.array([[1, 2], [3, 4]]).ravel()

array([1, 2, 3, 4])

이렇게 펼친 후에 `reshape()`를 사용하던가, 아니면 모양을 보고 직접 배열의 모양을 바꿔주면 됩니다.

#### 축을 추가하기

`reshape()`는 단순히 모양을 지정하는 역할을 수행할 뿐 아니라, 길이가 1인 새로운 축을 추가하는 역할도 합니다.

위에서도 설명했었는데, 행벡터 및 열벡터는 모양이 `(1,n)` 및 `(n,1)`인 2차원 배열로 생각하는 경우가 많다고 했었습니다.

그건 결국 수학적 연산에 맞춰주기 위함이라는 목적이 있었는데요, 그렇다고 그 행벡터/열벡터를 구성하는 성분들은 1차원 배열의 형태나 다름없는데요,

1차원 배열(즉, 벡터의 성분들의 정보)가 주어지는 경우에 우리는 `reshape((1,n))`, `reshape((n,1))`로 1차원 배열을 행벡터/열벡터화 할 수 있습니다.

이런 역할은 `reshape()`를 사용할 수도 있으나, 그냥 간단하게 배열에 인덱싱을 하는 테크닉을 이용할 수도 있어요.

~~~python
arr[... : , None, :...]
~~~

그 방법은 저렇게 축을 추가하고 싶은 위치에 그냥 `None`을 넣고, 나머지엔 빈 슬라이싱을 넣어주면 끝입니다.

예를 들어서 1차원 배열은 다음과 같이 열벡터 및 행벡터로 바꿔줄 수 있습니다.

In [54]:
a = np.arange(3) # [0, 1, 2] 형태의 1차원 배열
b = a[None, :]  # 행 부분에 None을 넣고, 열 부분에는 그냥 빈 슬라이싱

print(b.shape) # 그러면 b는 모양이 1x3인 행벡터 형태의 2차원 벡터가 됩니다.
b 

(1, 3)


array([[0, 1, 2]])

In [55]:
b = a[:, None] #마찬가지로 열벡터
print(b.shape) 
b

(3, 1)


array([[0],
       [1],
       [2]])

#### 배열의 전치(Transpose)

배열의 전치는 행렬의 전치를 생각하시면 됩니다. 행렬 $A$의 전치 $A^T$는 다음을 의미합니다.
$$
A = \begin{pmatrix}
1 & 2 &3\\
4& 5& 6\end{pmatrix}\quad \Rightarrow \quad A^T = \begin{pmatrix} 1 & 4 \\ 2 & 5 \\ 3 &6\end{pmatrix}
$$

행렬이 $n$행 $m$열이었다면, 이걸 $m$행 $n$열로 바꾸고, 각 성분들도 $i$행 $j$열의 성분을 $j$행 $i$열의 성분으로 바꾸는거죠.

얼핏보면 이 과정이 그냥 `reshape()`처럼 보이지만, 그렇지가 않습니다.

In [56]:
A = np.array([
                [1,2,3],[4,5,6]
             ])
A

array([[1, 2, 3],
       [4, 5, 6]])

이런 `A`에 그저 `reshape()`만 한다면, 다음의 모양이 되거든요 : 

In [57]:
A.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

그냥 말 그대로 모양만 $n$행 $m$열을 $m$행 $n$열로 바꾸고, 성분은 그대로 둡니다.

이렇게 성분의 위치도 바꿔주는 친구는 다음과 같습니다.

~~~python
arr.T
arr.transpose()  # arr.T는 이 arr.transpose()의 축약어입니다.
~~~

근데 "성분의 위치를 바꿔준다"라는 표현을 주의하셔야합니다. 마치 실제로 성분이 변하는거 같으나, 그렇지는 않아요.

실제로 성분의 위치를 바꿔주려면, 우리는 기존의 `arr`에 들어있는 성분 정보를 따로 저장해뒀다가, 일일이 위치를 다시 잡아줘야합니다.

그러면 추가적인 저장 공간이 필요할건데요, 그걸 피하기 위해서 NumPy는 이 단계까지도 전치 배열을 `View`로 남겨서, 보는 형태만 변경한 채로 유지시킵니다.

In [58]:
a = np.arange(20).reshape((5, -1))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [59]:
a.transpose()

array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])

In [60]:
np.arange(24).reshape((3, 8)).T

array([[ 0,  8, 16],
       [ 1,  9, 17],
       [ 2, 10, 18],
       [ 3, 11, 19],
       [ 4, 12, 20],
       [ 5, 13, 21],
       [ 6, 14, 22],
       [ 7, 15, 23]])

위에서는 모든걸 행렬, 즉 2차원 배열의 기준으로 설명했는데, 당연히 전치는 3차원 이상에서도 사용 가능합니다.

이 때는 행렬의 `shape`의 순서만 바꿔줍니다. 

예를 들어 3차원 배열의 shape는 `(depth, row, column)`이지만, 전치시 `(column, row, depth)`의 모양이 됩니다.

In [61]:
a = np.arange(24).reshape((2, 3, 4))
a.transpose().shape

(4, 3, 2)

물론 저건 기본적으로 저렇게 바꾼다는 이야기구요, 우리가 임의로 바꾸는 방식을 정해줄 수도 있습니다 :

In [62]:
a.transpose((0, 2, 1)).shape # 이 말은 3차원 배열인 a를 depth, column, row의 형태로, depth는 그대로 두고 행과 열만 전치시킨다는 소리

(2, 4, 3)

## 배열의 연산

배열은 수학적인 목적으로 사용되는 놈임에 따라서, `+`, `-`, `*`, `**`, `/`, `//`, `==` 등 수학적인 연산을 지원합니다. 

이런 이항 연산은 원칙적으로 두 배열의 순서에 맞는 성분들끼리 성분별로 계산됩니다

In [63]:
np.arange(0,5) == np.arange(0,5) # 배열의 각 성분별로 연산이 적용됩니다. 성분의 개수(shape)가 맞지 않으면 오류

array([ True,  True,  True,  True,  True])

그리고 굳이 배열간의 연산이 아니라, 숫자(스칼라)와 배열간의 연산도 가능합니다 :

In [64]:
10 * np.arange(3)

array([ 0, 10, 20])

위의 이항 연산들과 비슷하게 함수들도 성분별로 값들을 변경해주는 친구들이 있습니다.

이러한 함수들은 유니버셜 함수(universal function)이라고도 합니다.

In [65]:
np.sin(np.arange(5)) # 유니버셜 함수

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [66]:
[np.sin(t) for t in np.arange(5)] # 물론 기존의 컴프리헨션으로 하신 후, 이걸 배열화해도 상관없긴합니다.

# 하지만 이 경우, for 루프를 사용한다는 점과 불필요한 리스트가 생성된다는 단점이 있습니다.

[np.float64(0.0),
 np.float64(0.8414709848078965),
 np.float64(0.9092974268256817),
 np.float64(0.1411200080598672),
 np.float64(-0.7568024953079282)]

## 행렬/벡터 연산

배열은 행렬과 벡터를 모델링할 수 있는 구조이기 떄문에, 행렬과 벡터에 관한 가장 기본적이고 인기가 많은 연산도 이미 내장되어 있습니다.

대부분은 NumPy 모둘의 함수로서 존재하기도 하구요, 기본적인 벡터-행렬간의 곱이라던지 사칙 연산 등은 연산자 형태로도 사용 가능합니다.

예를 $A \in \mathbb{R}^{2 \times 2}$ $x \in \mathbb{R}^2$가 다음의 형태로 주어졌다고 해보죠.
$$
A = \begin{pmatrix} 1 & 2 \\ 3 & 4 \end{pmatrix}, \quad x = \begin{pmatrix} 5 \\ 6 \end{pmatrix}
$$
그러면 두 놈의 곱 $y = Ax$는 다음과 같이 계산 가능합니다.

In [67]:
import numpy as np
A = np.array([[1, 2], [3, 4]])
x = np.array([5, 6])

# dot() 메소드를 사용하기
y = A.dot(x)
print('A.dot(x) = ', y)

# dot()을 함수로 사용하기
y = np.dot(A, x)
print('dot(A,x) = ', y)

# 연산자 @를 사용하기
y = A @ x
print('A@x  = ', y)

A.dot(x) =  [17 39]
dot(A,x) =  [17 39]
A@x  =  [17 39]


참고로 `A*x`는 다른 연산입니다 : 

In [68]:
z = A*x
print('A*x =', z)

A*x = [[ 5 12]
 [15 24]]


이 놈은 브로드캐스팅(Broadcasting)이라고 해서, 수학적인 행렬과 벡터의 곱이 아니라, 성분의 위치를 매칭시켜서 성분별로 곱하는 형태가 됩니다.

당연히 우리는 저런 간단한 놈들 말고 좀 더 복잡한 연산도 가능합니다.

In [69]:
b = np.array([6, -4, 27])
c = np.array([1, 2, 3])
print(b @ c)

79


위와 같이 `b`, `c`를 정의하고 `b@c`를 하면, 우리가 기본적으로 알고 있는 스칼라 곱이 됩니다. 성분별로 곱한 후 더해서 반환하는거죠.

이는 당연히 위에서 다룬 `np.dot(b,c)`와 같이 `dot()` 함수로도 사용할 수 있습니다.

외적은 간단하게, 반대로 $m$행 1열의 열벡터와 $1$행 $n$열의 행벡터를 곱하여 행렬을 만드는건데요,

이는 예를 들어 다음을 의미합니다.
$$
\begin{pmatrix} 6 \\ -4 \\ 27 \end{pmatrix} \begin{pmatrix} 1 & 2 & 3 \end{pmatrix} = \begin{pmatrix}6 & 12 & 18 \\ -4 & -8 & -12\\ 27 & 54&81\end{pmatrix}
$$

이거도 기존의 연산자 `@`를 이용하면 되는데요, 다만 이 때는 1차원 배열은 안되고, 2차원 배열로 벡터를 열벡터/행벡터화해야합니다 :

```python
b[:, None] @ c[None, :]
```

In [70]:
b = b[:,None]
c = c[None, :]
b@c

array([[  6,  12,  18],
       [ -4,  -8, -12],
       [ 27,  54,  81]])

행/열벡터화는 위에서도 다룬대로 슬라이스를 이용한 트릭으로 간단히 해결 가능합니다.

참고로 `dot()`함수는 더 이상 사용할 수 없습니다. 대신 외적은 `outer()`함수를 사용하시면 됩니다 :
```python
np.outer(b, c)
```

In [71]:

print(np.outer(b, c))

[[  6  12  18]
 [ -4  -8 -12]
 [ 27  54  81]]


## 더 많은 다양한 연산들

그 외에도 행렬에는 행렬식이라던지, 역행렬, 고유값 및 고유 벡터, 선형 방정식을 푸는 등의 기능들이 NumPy에 내장되어 있습니다.

- `np.linalg.det` 행렬의 행렬식을 계산
- `np.linalg.inv` 역행렬을 계산
- `np.linalg.solve` 선형 방정식을 푸는 놈
- `np.linalg.eigen` 고유값 및 고유 벡터를 계산(각각 배열에 담아서 투플로 반환)
- `np.linalg.matrix_rank` 행렬의 계수를 계산
- 기타 등등

얘네들은 전부 \[선형대수학\]의 개념이다보니. 위와 같이 `np.linalg`라는 NumPy의 서브 모둘에 있습니다.

사용법은 아래 코드를 참고해주세요

In [72]:
A = np.array([[1, 1 , 1], [0, 2, 5], [2, 5, -1]])
Ainv = np.linalg.inv(A) # 역행렬
print(Ainv)
print(A @ Ainv,'\n\n') 

print("A의 행렬식 :", np.linalg.det(A)) # 행렬식
print("A의 계수 :", np.linalg.matrix_rank(A)) #계수

x = np.linalg.solve(A, b)
print("Ax = b의 해 :", x)
print("검산 ", A @ x - b)
print("역행렬을 통한 해의 계산 ", np.linalg.inv(A) @ b)

print("고유값", np.linalg.eig(A)[0])
print("고유 벡터", np.linalg.eig(A)[1])


[[ 1.28571429 -0.28571429 -0.14285714]
 [-0.47619048  0.14285714  0.23809524]
 [ 0.19047619  0.14285714 -0.0952381 ]]
[[ 1.00000000e+00 -5.55111512e-17  0.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [-2.22044605e-16  5.55111512e-17  1.00000000e+00]] 


A의 행렬식 : -21.0
A의 계수 : 3
Ax = b의 해 : [[ 5.]
 [ 3.]
 [-2.]]
검산  [[0.]
 [0.]
 [0.]]
역행렬을 통한 해의 계산  [[ 5.]
 [ 3.]
 [-2.]]
고유값 [-4.77879032  0.72601723  6.05277309]
고유 벡터 [[ 0.03651873 -0.93496706 -0.26817252]
 [ 0.59319558  0.34375159 -0.74839768]
 [-0.80422969 -0.08758672 -0.60661719]]


\[선형대수학\]에서 벡터들이 선형 독립임은 그 놈들을 열벡터로 하는 함수들이 꽉찬 계수를 가짐으로도 표현 가능했는데요,

이를 이용하여 위의 `np.linalg.matrix_rank()`함수로 계수를 계산하는 방법으로 선형 독립성도 판별이 가능합니다.

In [73]:
vec = [ np.array([1, 2, 3]), np.array([4, 5, 6]), np.array([7, 8, 9]) ]
vec_matrix = np.stack(vec, axis=0)
print(np.linalg.matrix_rank(vec_matrix))

2


위 행렬은 계수가 2네요? 3이어야 독립인데 말이죠. 이렇게 독립성 판별도 가능합니다.

예를 들어 다음과 같이 독립성을 판별하는 함수도 정의할 수 있습니다.

```python
def independ(veclst) :
    matrix = np.stack(veclst,axis = 0)
    return np.linalg.matrix_rank(matrix) == len(veclst)
```

In [74]:
def independ(veclst) :
    matrix = np.stack(veclst,axis = 0)
    return np.linalg.matrix_rank(matrix) == len(veclst)

vec = [ np.array([1, 2, 3]), np.array([4, 5, 6]), np.array([7, 8, 9]) ]
independ(vec)

np.False_

## 축소(Reduction)

축소는 배열의 하나 혹은 복수의 축을 따라서 값들을 조합하는 연산을 의미합니다.

대부분의 축소 연산들은 이름처럼 배열의 크기를 축소시킵니다.


#### 합, 곱 등등

가장 기초적인 축소 연산은 다음과 같습니다. 

~~~python
arr.sum(axis=None)   # 배열 성분들의 합
arr.prod(axis=None)  # 배열 성분들의 곱
arr.max(axis=None)   # 배열 성분들의 최대값
arr.min(axis=None)   # 배열 성분들의 최소값
arr.mean(axis=None)  # 배열 성분들의 평균
~~~

저기 보이시는 `axis`에 뭐가 들어가는지에 따라서 해당 연산들은 특정 축을 기준으로 할지, 아니면 모든 축을 다 고려할지가 결정됩니다 :

-   `None` (디폴트임): 진짜 모든 배열 원소들을 다 고려해라
-   `int`형의 숫자 객체 : 해당 숫자의 축 방향의 원소들만을 고려해라(2차원인 경우, 0은 행, 1은 열, 3차원은 0은 깊이, 1은 행, 2는 열 ...)
-   `int`형의 숫자들의 투펠 : 입력된 숫자들의 축 방향의 원소들을 동시에 고려해라

In [75]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [76]:
a = np.arange(2*3*4)
a.sum()

np.int32(276)

In [77]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [78]:
a = np.arange(2*3*4).reshape((2, 3, 4))
a.sum()

np.int32(276)

In [79]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [80]:
a.sum(axis=0)

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [81]:
a.sum(axis=(1, 2))

array([ 66, 210])

#### 최대값/최소값의 인덱스

축소 연산 중에서는 최대값/최소값을 계산하는 것 뿐아니라, 그 지점을 반환하는 연산도 있습니다 :

~~~python
array_object.argmax(axis=None)
array_object.argmin(axis=None)
~~~

수학이랑 똑같이 $\arg\max$, $\arg\min$ 메소드는 각각 최대값/최소값의 지점을 반환합니다.

axis의 매개변수 규칙은 위의 다른 친구들과 동일합니다.

In [82]:
np.array([0, 1, 3, 2]).argmax()

np.int32(2)

## 모둘의 함수 이름들

만약 모둘로부터 특정 함수를

```python
from Modul import Function

```
의 방법으로 불러온다면, 우리는 이 함수 `Fucntion`을 `Modul.Function`없이, 우리의 스코프에서 그대로 `Function`으로 사용할 수 있습니다.

또 다음의 방법을 사용한다면, 해당 모둘의 모든 구성 요소들을 우리의 스코프에 가져오게 됩니다.

```python
from Modul import *
```

그러면 그 모둘의 모든 함수/클래스/변수는 `Modul.`을 자꾸 안붙여도 그대로 사용 가능합니다. 편리하죠.

하지만 편리해지는 만큼, 문제가 생길 가능성도 증가합니다.

만약 우리의 스코프에 이미 같은 이름인 함수/클래스/변수가 존재한다면, 위의 명령어는 이를 덮어씌워서, 임포트된 함수로 만들어버리거든요.

`from Modul Import` 로 임포트된 애들은 나중에 임포트 된 놈이 제일 최우선으로 다뤄지기 떄문에, 예상치 않은 문제가 발생할 수 있습니다.

예를 들어 `sin`이라는 함수는 `numpy`에도 있고, `math`에도 있거든요? 우선 `numpy`의 친구 먼저 사용해볼게요.

In [83]:
from numpy import sin

sin(np.ones(3))

array([0.84147098, 0.84147098, 0.84147098])

그러면 결과는 우리가 예상한대로, `sin`은 유니버셜 함수이니 `np.ones(3)`의 각 성분에 `sin`을 적용한 값들을 넣은 배열이 됩니다.

그런데 여기서 만약 `math`를 임포트해온다면, 다음과 같은 문제가 생깁니다.

In [84]:
from math import *

sin(np.ones(3))

<class 'TypeError'>: only length-1 arrays can be converted to Python scalars

우리는 기존에 NumPy의 `sin`을 사용하다가, `math`의 `sin`을 임포트해오니, 파이썬은 `sin`함수를 가장 최근에 임포트한 `math`의 `sin`으로 인식합니다.

그런데 `math`의 `sin`에는 배열을 넣을 수 없거든요? 그래서 저런 문제가 발생합니다.

이러한 점을 주의하셔서 사용하셔야합니다. 진짜 웬만하면 그냥 `import Modul as Name`에서 `Name`을 짧게 설정하여 쓰는 방법이 나을 수도 있어요.